image: node:6.9.0

before_script:
  - git config --global user.email "i@hzhou.me"
  - git config --global user.name "Hao Zhou"

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - hexo g
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
