# Header
menu:
  Home: /
  LeetCode: /LeetCode
  About: /about
  RSS: /atom.xml

# Content
excerpt_link: Read More
prev: Prev
next: Next
fancybox: true

# Sidebar
widgets:
- search
- notice
- about
- recent_posts
- archive
- category
- tagcloud
- link

# Miscellaneous
google_analytics:
disqus_shortname: zhouhao
rss: /atom.xml
favicon: /favicon.png
subtitle: "咸蛋，请赐予我力量吧~"
